### ISSUE TITLE
About Similarity Pyramid

### ISSUE THREAD

**Issue by Tclz** [Paranioar/SGRAF#4]
Hi, Could you please me how to understand the **Similarity Pyramid(and Pyramid Spatial Window, different Pyramid Levels, etc.)** which used in obtaining image feature that your paper memtioned???
 In your released code, it was only region features extracted by Faster-RCNN(Bottom-up Attention)just as the Pioneers' work?  I'm confused about that. 
Thank you in Advance! :)

**Comment by Paranioar** [comment]
> Hi, Could you please me how to understand the **Similarity Pyramid(and Pyramid Spatial Window, different Pyramid Levels, etc.)** which used in obtaining image feature that your paper memtioned???
> In your released code, it was only region features extracted by Faster-RCNN(Bottom-up Attention)just as the Pioneers' work? I'm confused about that.
> Thank you in Advance! :)

I'm sorry. I didn't catch your meaning.
The image feature is computed by the self-attention mechanism on region features. 

In brief, the motivation of different alignment levels is that:
The distance between the image and its positive text is still relatively large, because the content of the former is much richer than the latter, while the one between the semantic word and its corresponding regions can be very close. We aggregate all meaningful alignments from the perspective of the text(or semantic words), resulting in a larger gap between positive and negative pairs.
